// @ts-check
// Manual sidebars — one per audience-oriented section (hybrid of the
// dharmamitra-guides tool-catalog shape and Cologne-specific workflows).

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  usersSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Using the Site',
      collapsed: false,
      items: [
        'users/quick-start',
        'users/first-sanskrit-sentence',
        'users/using-the-website',
        'users/search-and-display',
        'users/encoding-transliteration',
        'users/transliteration-quiz',
        'users/devanagari-quiz',
        'users/sandhi-quiz',
        'users/samasa-quiz',
        'users/reading-monier-williams',
        'users/which-dictionary-quiz',
        'users/downloads-and-data',
        'users/scans-and-print',
        'users/troubleshooting',
        'users/newsletter',
      ],
    },
  ],

  dictionariesSidebar: [
    {
      type: 'category',
      label: 'Dictionaries',
      collapsed: false,
      items: [
        'dictionaries/overview',
        'dictionaries/catalog',
        'dictionaries/landscape',
        'dictionaries/citation-sources',
        'dictionaries/citation-graph',
        'dictionaries/corpus-attestation',
        'dictionaries/machine-morphology',
        'dictionaries/abbreviations-and-citations',
        'dictionaries/abbreviations-comparison',
        'dictionaries/ocr-prefaces',
        {
          type: 'category',
          label: 'Featured dictionaries',
          collapsed: false,
          items: [
            'dictionaries/mw',
            'dictionaries/mw72',
            'dictionaries/ap90',
            'dictionaries/ap',
            'dictionaries/wil',
            'dictionaries/cae',
            'dictionaries/md',
            'dictionaries/ben',
            'dictionaries/yat',
            'dictionaries/shs',
            'dictionaries/gst',
            'dictionaries/lrv',
            'dictionaries/ae',
            'dictionaries/bor',
            'dictionaries/bop',
            'dictionaries/bur',
            'dictionaries/fri',
            'dictionaries/lan',
            'dictionaries/pwg',
            'dictionaries/pw',
            'dictionaries/sch',
            'dictionaries/pwkvn',
            'dictionaries/ccs',
            'dictionaries/gra',
            'dictionaries/bhs',
            'dictionaries/stc',
            'dictionaries/mwe',
            'dictionaries/skd',
            'dictionaries/vcp',
            'dictionaries/abch',
            'dictionaries/acph',
            'dictionaries/acsj',
            'dictionaries/armh',
            'dictionaries/nmmb',
            'dictionaries/krm',
            'dictionaries/acc',
            'dictionaries/ieg',
            'dictionaries/inm',
            'dictionaries/mci',
            'dictionaries/pe',
            'dictionaries/pgn',
            'dictionaries/pui',
            'dictionaries/snp',
            'dictionaries/vei',
            'dictionaries/pd',
          ],
        },
      ],
    },
  ],

  toolsSidebar: [
    {
      type: 'category',
      label: 'Tools',
      collapsed: false,
      items: [
        'tools/overview',
        'tools/name-in-devanagari',
        'tools/sanskrit-level-quiz',
        'tools/word-game',
        'tools/simple-search',
        'tools/advanced-search',
        'tools/multi-dictionary',
        'tools/offline-stardict',
      ],
    },
  ],

  contributingSidebar: [
    {
      type: 'category',
      label: 'Contributing',
      collapsed: false,
      items: [
        'contributing/overview',
        'contributing/report-a-typo',
        'contributing/process-one-correction',
        'contributing/process-scott-batch',
        'contributing/corrections-workflow',
        'contributing/change-files',
        'contributing/issue-taxonomy',
      ],
    },
  ],

  developersSidebar: [
    {
      type: 'category',
      label: 'Developer Guide',
      collapsed: false,
      items: [
        'developers/architecture',
        'developers/repositories',
        'developers/generation-pipeline',
        'developers/data-formats',
        'developers/data-cards',
        'developers/data-hub',
        'developers/api',
      ],
    },
    {
      type: 'category',
      label: 'About',
      collapsed: true,
      items: [
        'about/about',
        'about/origins',
        'about/history',
        'about/events',
        'about/publications',
        'about/guides-hypotheses',
        'about/shared-tasks',
        'about/dh-programme',
        'about/acknowledgments',
        'faq',
      ],
    },
  ],
};

export default sidebars;
